// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Stark (https://sketchfab.com/stark3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/the-universe-ef1aa837c6fb480b8691c212a4d63d9d
title: The Universe!
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations, scene, universe } =
    useGLTF("/universe.gltf");
  // const { actions, mixer } = useAnimations(animations, group);
  let mixer: any;
  if (animations.length) {
    mixer = new THREE.AnimationMixer(scene);
    animations.forEach((clip) => {
      const action = mixer.clipAction(clip);
      action.play();
    });
  }

  useEffect(() => {
    // console.log(actions["-10s"]);
    // actions?.animate();
    console.log("mixer", mixer);
  }, []);

  useFrame((state, delta) => {
    mixer?.update(delta);
    // console.log("hey");
  });

  scene.traverse((node) => {
    //ts-ignore
    if (!node.isMesh) return;
    node.material.wireframe = true;
  });

  return <primitive object={scene} scale={0.035}></primitive>;
}

useGLTF.preload("/scene.gltf");
