//@ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Salvatore Orlando (https://sketchfab.com/sorlando)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/a-stellar-nursery-in-the-interstellar-space-dd8581835a0c4614b37cd508546daae3
title: A stellar nursery in the interstellar space
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/stellar.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[2, 1, 0]} rotation={[0, 1, 0]} scale={0.12}>
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_13}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material_12}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material_11}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material_10}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material_9}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.material_8}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.material_7}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.material_6}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.material_5}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.material_1}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/stellar.gltf");
